version: "3.8"

networks:
  web:
    external: true

services:
  traefik:
    image: traefik:v2.10
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.email=edgar.treischl@isb.bayern.de"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - web

  causalityapp:
    image: ghcr.io/edgar-treischl/causalityapp
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.causality.rule=Host(`causalityapp.edgar-treischl.de`)"
      - "traefik.http.routers.causality.entrypoints=websecure"
      - "traefik.http.routers.causality.tls.certresolver=le"
      - "traefik.http.services.causality.loadbalancer.server.port=3838"
    networks:
      - web
